

development:
  adapter: postgresql
  database: sebastian-valdez-site_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sebastian-valdez-site_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sebastian-valdez-site_development
  pool: 5
  timeout: 500